name = "v2ray-clash-bot" # Nama unik untuk Worker Anda
main = "src/index.js"  # Menunjuk ke file JavaScript utama Worker
compatibility_date = "2024-06-21" # Gunakan tanggal saat ini atau yang lebih baru
# Ini sangat penting untuk mengaktifkan Buffer dan beberapa API Node.js lainnya
compatibility_flags = ["nodejs_compat"]

# Variabel lingkungan untuk Worker.
# Anda disarankan menggunakan `wrangler secret put BOT_TOKEN`
# Atau atur di dashboard Cloudflare Workers (Worker Anda -> Settings -> Variables -> Add environment variable)
# Jangan hardcode token di sini jika Anda menggunakannya di produksi.
# [vars]
# BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN_HERE"
